### ISSUE TITLE
tracestate ows example fails before exercising service

### ISSUE THREAD

**Issue by toumorokoshi** [w3c/trace-context#341]
the test_tracestate_ows_handling raises a ValueError before exercising the service under test:

https://github.com/w3c/trace-context/blob/master/test/test.py#L640

The exception that is raised is:

```
Traceback (most recent call last):
  File "test.py", line 640, in test_tracestate_ows_handling
    ['tracestate', 'foo=1 '],
  File "test.py", line 113, in make_single_request_and_get_tracecontext
    return (self.get_traceparent(headers), self.get_tracestate(headers))
  File "test.py", line 108, in get_tracestate
    tracestate.from_string(value)
  File "/home/tsutsumi/workspace/opentelemetry-python/target/trace-context/test/tracecontext/tracestate.py", line 54, in from_string
    raise ValueError('illegal key-value format {!r}'.format(member))
ValueError: illegal key-value format 'foo=1 '
```

**Comment by reyang** [comment]
The error means the service being tested is not stripping training spaces in `tracestate` while calling back to the test harness.
