### ISSUE TITLE
Test suite server crashes with newer multidict version

### ISSUE THREAD

**Issue by Oberon00** [w3c/trace-context#366]
See https://github.com/open-telemetry/opentelemetry-python/issues/329:

```
py37-tracecontext installed: aiohttp==3.6.2,async-timeout==3.0.1,attrs==19.3.0,certifi==2019.11.28,chardet==3.0.4,Click==7.0,Flask==1.1.1,idna==2.8,itsdangerous==1.1.0,Jinja2==2.10.3,MarkupSafe==1.1.1,multidict==4.7.0,requests==2.22.0,urllib3==1.25.7,Werkzeug==0.16.0,yarl==1.4.2
...

test_traceparent_version_0xff (__main__.TraceContextTest) ... Error handling request
Traceback (most recent call last):
  File "/home/travis/build/open-telemetry/opentelemetry-python/.tox/py37-tracecontext/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/travis/build/open-telemetry/opentelemetry-python/.tox/py37-tracecontext/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/travis/build/open-telemetry/opentelemetry-python/target/trace-context/test/server.py", line 53, in scope_handler
    async with ClientSession(headers = headers, timeout = self.timeout) as session:
  File "/home/travis/build/open-telemetry/opentelemetry-python/.tox/py37-tracecontext/lib/python3.7/site-packages/aiohttp/client.py", line 268, in __init__
    real_headers = CIMultiDict(headers)  # type: CIMultiDict[str]
TypeError: CIMultiDict keys should be either str or subclasses of str
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7efcde7e8668>
ERROR
```

This starts happening with multidict==4.7.0, with the previous 4.6.1 it worked fine.

Maybe this is a bytestring vs string issue?

The version of this repository that was used is 98f210efd89c63593dce90e2bae0a1bdcb986f51.

**Comment by Oberon00** [comment]
This is probably no longer an issue, as it was a bug in multidict 4.7.0 that was fixed in subsequent patch releases. So if your tests are green, feel free to close this.
