### ISSUE TITLE
Fix key errors in test suite

### ISSUE THREAD

**Issue by srjames90** [w3c/trace-context#416]
When running the tests, you can get a failure due to the tests checking for keys in an empty dictionary. Below, is an example of the error message. Because no tracestate was passed along by the server, the tracestate map is empty and causes this error. I think it's kind of confusing to have both Failure and Errors states that indicate a failure. I think we should just check if the keys exist prior to accessing them.

```
ERROR: test_tracestate_included_traceparent_included (__main__.TraceContextTest)
harness sends a request with both tracestate and traceparent
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 785, in test_tracestate_included_traceparent_included
    self.assertEqual(tracestate['foo'], '1')
  File "/Users/stevenrivera-james/workspace/test_pr/lstracer-integration-tests/propagation-tests/propagation-server/tracecontext/tracestate.py", line 35, in __getitem__
    return self._traits[key]
KeyError: 'foo'
```

**Comment by srjames90** [comment]
I made a quick branch and PR attempting to fix this in case @reyang wants to work off that: https://github.com/w3c/trace-context/pull/417
